### ISSUE TITLE
webpay Package guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by AnitaSun** [webpay/webpay-php#17]
The install command below causes an error.
$ composer require webpay/webpay
"Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.".

And this also causes
<b>Fatal error</b>:  Uncaught Guzzle\Common\Exception\RuntimeException: The PHP cURL extension must be installed to use Guzzle. in /var/www/html/xxxxxx/vendor/guzzle/guzzle/src/Guzzle/Http/Client.php:72

How do I solve it?

**Comment by tomykaira** [comment]
Thank you for bug reporting.

The first warning is `webpay/webpay`'s problem. We must update dependencies. We need time to do that, but meanwhile, you may be able to use the current release.

The second problem is of your server machine. Your PHP install does not include cURL extension.
I cannot advice because there is no information about OS, version, etc. Google will help a lot. https://www.google.co.jp/search?q=The+PHP+cURL+extension+must+be+installed+to+use+Guzzle.&oq=The+PHP+cURL+extension+must+be+installed+to+use+Guzzle.&aqs=chrome..69i57j0l3.255j0j7&sourceid=chrome&ie=UTF-8
Because the problem is on your environment, I am sorry but we will not provide further help about this.

**Comment by AnitaSun** [comment]
Thank you for your response.
I understand what I should do.
